name: Build and Deploy to Pi

on:
    push:
        branches: [ "master" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: LocalPiServer
        steps:
            - name: Install cloudflared
              run: |
                wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                sudo dpkg -i cloudflared-linux-amd64.deb
            - name: SSH and Deploy
              run: |
                # 1. Setup SSH directory and private key
                mkdir -p ~/.ssh
                echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/pi_key
                chmod 600 ~/.ssh/pi_key

                # 2. Add Pi's host to known_hosts to avoid the "trust" prompt
                ssh-keyscan ${{ secrets.PI_SSH_HOST }} >> ~/.ssh/known_hosts

                # 3. Use SSH with the -o ProxyCommand flag, passing in your Service Token
                ssh -i ~/.ssh/pi_key -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname %h --service-token-id ${{ secrets.CF_CLIENT_ID }} --service-token-secret ${{ secrets.CF_CLIENT_SECRET }}" ${{ secrets.PI_SSH_USER }}@${{ secrets.PI_SSH_HOST }} << 'EOF'
                    cd /mnt/data/Projects/MarketMavenSocialTrends
                    docker compose pull
                    docker compose up -d
                EOF
